# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

build-master-backend:
  stage: build
  script:
    - cd backend
    - docker build --pull -t bonemind/crmirror-backend .
    - docker push bonemind/crmirror-backend
  only:
    - master

build-master-frontend:
  stage: build
  script:
    - cd frontend
    - docker build --pull -t bonemind/crmirror-frontend .
    - docker push bonemind/crmirror-frontend
  only:
    - master
