image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

build-develop-backend:
  stage: build
  script:
    - cd backend
    - docker build --pull -t bonemind/crmirror-backend:develop .
    - docker push bonemind/crmirror-backend
  only:
    - develop

build-develop-frontend:
  stage: build
  script:
    - cd frontend
    - docker build --pull -t bonemind/crmirror-frontend:develop .
    - docker push bonemind/crmirror-frontend
  only:
    - develop

build-tag-backend:
  stage: build
  script:
    - cd backend
    - docker build --pull -t "bonemind/crmirror-backend:$GIT_COMMIT_TAG" -t bonemind/crmirror-backend:latest .
    - docker push bonemind/crmirror-backend
  only:
    - tags

build-tag-frontend:
  stage: build
  script:
    - cd frontend
    - docker build --pull -t "bonemind/crmirror-frontend:$GIT_COMMIT_TAG" -t bonemind/crmirror-frontend:latest .
    - docker push bonemind/crmirror-frontend
  only:
    - tags
