version: '3'
services:
  web:
    build: frontend
    ports:
     - "5000:80"
    depends_on:
     - api

  api:
    build: backend
    environment:
       KEMAL_ENV: production
    depends_on:
     - db

  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_PASSWORD: crystal
      POSTGRES_DB: crystal
      POSTGRES_USER: crystal
