defaults :
  web: &web
    port: 3200
  db: &db
    host: localhost
    adapter: postgres
    user: crystal
    password: crystal
    database: crystal
    port: 5433
    migration_files_path: ./src/migrations
  ssh: &ssh
    keys_dir: /tmp/mirror_keys
  git: &git
    repo_dir: /tmp/git_mirrors
  dispatch: &dispatch
    queue_size: 1000
    workers: 5

development:
  web:
    <<: *web
  db:
    <<: *db
    database: crystal
  ssh:
    <<: *ssh
  git:
    <<: *git
  dispatch:
    <<: *dispatch

production:
  web:
    <<: *web
  db:
    <<: *db
    host: db
    database: crystal
  ssh:
    <<: *ssh
  git:
    <<: *git
  dispatch:
    <<: *dispatch

test:
  web:
    <<: *web
  db:
    <<: *db
    database: crystal
    user: something
  ssh:
    <<: *ssh
  git:
    <<: *git
  dispatch:
    <<: *dispatch
